version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    command: >
      --tlsMode=allowTLS
      --tlsCertificateKeyFile=/etc/ssl/server.pem
      --auth
      --setParameter authenticationMechanisms=PLAIN,SCRAM-SHA-1
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ds-mongo-data:/data/db
      - .certs/mongodb:/etc/ssl:ro
    networks:
      - ds-network
    logging:
      driver: json-file
      options:
        max-size: 100m
  back:
    build: .
    container_name: ds-back
    restart: always
    environment:
      - AUTH_SECRET=${AUTH_SECRET}
    ports:
      - 3001:3001
      - 8082:8082
    volumes: 
      - ./.certs/ds-back/:/usr/src/ds/.certs/:ro
    networks:
      - ds-network
    logging:
      driver: json-file
      options:
        max-size: 100m

volumes:
    ds-mongo-data:
        name: ds-mongo
networks:
  ds-network:
    name: ds-network
    driver: bridge